export const urls = {
    getUsers: 'admin/get-all-users/',
    changePassword : 'admin/change-password/',
    updateProfile:'admin/update-profile/',
    getBankDetails:'admin/get-all-banks-with-pagination/',
    createBank:'admin/create-bank/',
    deleteBank:'admin/delete-bank-by-pk/',
    changeStatus:'admin/accept-reject--user-by-userid/',
    changeFlag:'admin/change-flag-status-by-userid/',
    deleteUser:'admin/delete-user-by-pk/',
    addUser:'admin/add-user/',
    addMedia:'upload/media/',
    getUserById:'admin/get-user-by-pk/',
    getAllCurrency:'admin/get-all-currencies/',
    updateCurrency:'admin/update-currency-rates-by-pk/',
    updateUserById:'admin/update-user-by-id/',
    searchBank:"admin/search-bank/",
    adminbakDetails:"admin/add-update-bank-details/",
    getDashboard:'admin/get-admin-dashboard-counts/',
    getRevenueGraph:'admin/get-total-revenue-graph/',
    getOrderGraph:'admin/get-total-orders-graph/',
    getNewOrderGraph:'admin/get-new-orders-graph/',
    getReferalAmount:'admin/get-referal-amount/',
    updateReferalAmount:'admin/add-update-referal-code-amount/',
    getReferalHistory:'admin/get-referal-amount-history/',
    deleteAmountHistory:'admin/delete-referal-amount-history/',
    getUserReferHistory:'admin/get-user-refer-history/',
    getWalletAddress:'admin/get-wallet-addresses/',
    updateWalletAddress:'admin/update-wallet-address/',
};